### ISSUE TITLE
Anomalie des modifications dans les fichiers DATAGOUV.

### ISSUE THREAD

**Issue by vchalmel** [139bercy/format-commande-publique#51]
Suite à de nombreuses erreurs en tentant d'utiliser les xsd fournis pour parser les fichiers DATAGOUV je me suis rendu compte qu'ils ne respectent pas le format prescrit. 

En particulier, des blocs de modifications de marches contiennent des champs réservés aux modifications de contrats de concessions (dateSignatureModification notamment)

**Comment by ColinMaudry** [comment]
L’obligation de publication des données d’attribution ont causé et causent toujours pas mal de difficultés aux agents qui saisissent les données et aux collectivités qui les publient. Nous avons choisi de ne pas conditionner la publication des données à la validité afin de ne pas invisibiliser ces problèmes.

Avec le Ministère des Finances, nous réfléchissons à une politique de publication qui permette à la fois la publication de toutes les données rendues publiques (comme aujourd’hui sur data.gouv.fr : https://www.data.gouv.fr/fr/datasets/5cd57bf68b4c4179299eb0e9/), mais également à la mise à disposition d’un sous-ensemble plus qualitatif pour des cas d’usage exigeants. Dans ce cadre, les données seront vérifiées, les champs inutiles supprimés, les codes SIRET, CPV, postaux, etc. seront vérifiés.

Soit les données pourront être redressées, soit les marchés concernés seront retirés.

Ma réponse répond-elle à votre question ?

**Comment by vchalmel** [comment]
Il me semble oui. Dans mon cas la meilleure conduite à tenir est que j'identifie manuellement les cas les plus problématiques et de remplacer manuellement ces tags inadéquats par leur plus proche équivalent dans le schéma.
